{{- range .Values.branches }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}-hpc-docs
  labels:
    app.kubernetes.io/app: hpc-docs
    app.kubernetes.io/instance: {{ .name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/app: hpc-docs
      app.kubernetes.io/instance: {{ .name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/app: hpc-docs
        app.kubernetes.io/instance: {{ .name }}
    spec:
      containers:
      - name: nginx
        image: hub.k8s.ucar.edu/hpc-docs/hpc-docs:{{ .imageTag }}
        ports:
        - containerPort: 80
---
{{- end }}