name: Build and push container image

on: 
  workflow_dispatch:

jobs:
  buildpush:
    name: Build and push image
    runs-on: 
      group: CIRRUS-4x8
    
    steps:
    - name: Get short sha
      run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

    - name: Checkout Repo
      uses: actions/checkout@v5
      with:
        path: repo
        submodules: 'true'
        fetch-depth: 0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/amd64
        driver: remote
        endpoint: tcp://buildkitd.arc-systems:1234

    - name: registry login
      uses: docker/login-action@v3
      with:
        registry: hub.k8s.ucar.edu/hpc-docs
        username: ${{ secrets.hub_user }}
        password: ${{ secrets.hub_password }}

    - name: Build
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: hub.k8s.ucar.edu/hpc-docs/hpc-docs:${{ env.SHORT_SHA }}
        file: repo/container/Containerfile
        context: repo/
  deploy:
    name: Deploy branches to cirrus
    runs-on:
      group: CIRRUS-4x8
    
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v5
      with:
        path: repo
        fetch-depth: 0

    - name: Get branch and hash list
      run: |
        /usr/bin/bash
        cd repo
        for b in `git branch -r|grep -v HEAD|grep -E 'cirrus|main'|cut -d '/' -f2`; do
          hash=`git log -1 --pretty=format:%H origin/$b --`
          echo $b,${hash:0:7}
          echo $b,${hash:0:7} >> /tmp/hash
          done
        echo "Wrote hash file"
        cat /tmp/hash
        /opt/micromamba/bin/pip install pyyaml
        /opt/micromamba/bin/python container/update_yaml.py container/chart/values.yaml
        cat container/chart/values.yaml